### ISSUE TITLE
请教使用方法？

### ISSUE THREAD

**Issue by taikong089** [xuncv/91porn-spider#1]
colly 这个库不能下载到，下载就报错，新手，不会go语言，麻烦大神给个教程

**Comment by xuncv** [comment]
这是基于go mod的工程。
运行 go mod tidy ， 下载依赖。
然后 go build 编译

**Comment by taikong089** [comment]
我再运行go mod tidy的时候 总是提示超时，\91porn-spider-master\91porn-spider-master\go.mod:6:2: require github.com/gocolly/colly: reading https://athens.azurefd.net/github.
com/gocolly/colly/@v/v2.1.0.info: 504 Gateway Timeout

**Comment by taikong089** [comment]
GOROOT=C:\Go #gosetup
GOPATH=C:\Users\JokerVic\go #gosetup
C:\Go\bin\go.exe test -json ./... #gosetup
go: errors parsing go.mod:
C:\Users\JokerVic\Desktop\导学资料\91porn-spider-master\91porn-spider-master\go.mod:6:2: require github.com/gocolly/colly: Get "https://proxy.golang.org/github.com/gocolly/colly/@v/v2.1.0.info": dial tcp 34.64.4.113:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.


我再运行编译的时候，就报错了···

**Comment by xuncv** [comment]
增加了release页。可以下载我编译过的
[https://github.com/xuncv/91porn-spider/releases/tag/v0.1](https://github.com/xuncv/91porn-spider/releases/tag/v0.1)

**Comment by taikong089** [comment]
**感谢大神**
